### ISSUE TITLE
javax.net.ssl.SSLException: Unsupported or unrecognized SSL message

### ISSUE THREAD

**Issue by bitbythecron** [kwart/simple-syslog-server#19]
I have two machines on the same home LAN. Machine 1 has IP of `192.168.0.12` and Machine 2 has an IP of `192.168.0.14`.

On Machine 2 (the syslog server running this project) I build the project via `mvn package` and then run it out of the `target` directory via `java -jar simple-syslog-server.jar tls`. Then back on Machine 1 (the syslog "client") I run:
```
nc -w0 192.168.0.14 9898 <<< "<34>1 2003-10-11T22:14:15.003Z mymachine.example.com su - ID47 - BOM'su root' failed for lonvick on /dev/pts/8"
```
Back on Machine 2 I get SSL-related errors. Here is the exact console output from Machine 2:
```
java -jar simple-syslog-server.jar tls
Simple syslog server (RFC-5424)
Usage:
  java -jar simple-syslog-server.jar [protocol]

Possible protocols: udp, tcp, tls

Starting Simple Syslog Server

Protocol:     tls
Bind address: 0.0.0.0
Port:         9898
Creating Syslog server socket


Handling Syslog client /192.168.0.12
javax.net.ssl.SSLException: Unsupported or unrecognized SSL message
  at java.base/sun.security.ssl.SSLSocketInputRecord.handleUnknownRecord(SSLSocketInputRecord.java:451)
  at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:175)
  at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:110)
  at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1418)
  at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1324)
  at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:440)
  at java.base/sun.security.ssl.SSLSocketImpl.ensureNegotiated(SSLSocketImpl.java:829)
  at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:920)
  at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:252)
  at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:271)
  at com.github.kwart.syslog.TCPSyslogSocketHandler.run(TCPSyslogSocketHandler.java:89)
  at java.base/java.lang.Thread.run(Thread.java:836)
```

Do I need to change the message format for TLS?

**Comment by kwart** [comment]
To use with the `nc` you have to run the syslog server without TLS encryption. i.e. `java -jar simple-syslog-server.jar tcp`

If you need/want to use TLS you could use `openssl s_client` (with proper arguments) instead of the netcat (`nc`).

**Comment by bitbythecron** [comment]
Thank you for responding to my tickets so quickly. Please bear with me as I am new to the syslog protocol! I think these tickets will have value for other users who might experience similar exceptions. But what an amazing project here, thank you!
