### ISSUE TITLE
Error 502

### ISSUE THREAD

**Issue by ognjen-it** [kwart/simple-syslog-server#4]
Hello,

When I try to deploy JAR file to Pivotal Cloud Foundry, I had some problems with conf (set TCP as default and change the port number to 8080) but I solved that. So, now I get 502 in log and I cannot resolve why this happened?

There are modified logs:

`2020-05-19T14:54:39.184+08:00 [CELL/0] [OUT] Container became healthy
2020-05-19T14:54:39.515+08:00 [APP/PROC/WEB/0] [OUT] Handling Syslog client /10.1.1.10
2020-05-19T14:54:48.574+08:00 [RTR/3] [OUT] java-syslog-service.myurl.com - [2020-05-19T12:54:45.571+0000] "OPTIONS /cloudfoundryapplication HTTP/1.1" 502 0 67 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36" "55.66.77.88:2206" "10.1.1.10:61001" x_forwarded_for:"11.22.33.44, 55.66.77.88" x_forwarded_proto:"https" vcap_request_id:"123" response_time:2.002447003 app_id:"123" app_index:"0" x_b3_traceid:"123" x_b3_spanid:"123" x_b3_parentspanid:"-" b3:"123-123"
`

**Comment by kwart** [comment]
Is your problem related to the simple-syslog-server? HTTP 502 is an error on web server side.

**Comment by ognjen-it** [comment]
I just push simple-syslog-server and didn't do anything.
Also, I got the next logs:
`2020-05-20T17:18:48.547+08:00 [APP/PROC/WEB/0] [OUT] Handling Syslog client /10.1.1.10
2020-05-20T17:18:48.551+08:00 [APP/PROC/WEB/0] [ERR] Exception in thread "Thread-2951" java.lang.StringIndexOutOfBoundsException: String index out of range: -34
2020-05-20T17:18:48.551+08:00 [APP/PROC/WEB/0] [ERR] at java.lang.String.checkBounds(String.java:381)
2020-05-20T17:18:48.551+08:00 [APP/PROC/WEB/0] [ERR] at java.lang.String.<init>(String.java:425)
2020-05-20T17:18:48.551+08:00 [APP/PROC/WEB/0] [ERR] at org.jboss.test.syslog.Rfc5424SyslogEvent.getString(Rfc5424SyslogEvent.java:138)
2020-05-20T17:18:48.551+08:00 [APP/PROC/WEB/0] [ERR] at org.jboss.test.syslog.Rfc5424SyslogEvent.<init>(Rfc5424SyslogEvent.java:75)`

If you know anything, please write to me :)

**Comment by ognjen-it** [comment]
@kwart where logs are stored?

**Comment by kwart** [comment]
The messages are just printed to the console. See
https://github.com/kwart/simple-syslog-server/blob/master/src/main/java/org/jboss/test/syslog/TCPSyslogSocketHandler.java#L126

**Comment by kwart** [comment]
Is your syslog mesage properly formatted? It seems the server fails to read hostname from the message.

**Comment by ognjen-it** [comment]
@kwart Syslog messages are formatted by Pivotal..
I got this message even if I didn't forward messages to syslog service.
Can this syslog handling  java stack trace?
Can I allow both TCP and UDP protocols?

**Comment by kwart** [comment]
Does Pivotal use the RFC-5424 format?
Not sure about the stacktraces.
You can't start TCP+UDP from the command line. If you need alignments, just change the code to fit your needs or you can use the Syslog4J directly.

**Comment by ognjen-it** [comment]
@kwart Sorry, I forgot to answer you. We changed the strategy and didn't want to use the syslog server for this.
btw, Pivotal used the RFC-5424 format, we have gotten information from pivotal/microservices, but the format was strange.
Thank you for your support.
